apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-config-local
data:
  DB_NAME: mydatabase
  DB_USERNAME: myuser
  DB_HOST: "postgresql-service"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: coworking-secret-local
type: Opaque
data:
  dbPassword: bXlwYXNzd29yZA==