apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-config
data:
  DB_NAME: mydatabase
  DB_USERNAME: myuser
  DB_HOST: "10.100.64.83"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: coworking-secret
type: Opaque
data:
  dbPassword: bXlwYXNzd29yZA==