apiVersion: v1
kind: Service
metadata:
  name: coworking-service
spec:
  type: LoadBalancer
  selector:
    service: coworking-service
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking-deployment
  labels:
    name: coworking-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking-service
  template:
    metadata:
      labels:
        service: coworking-service
    spec:
      containers:
      - name: coworking
        image: 550926655855.dkr.ecr.us-east-1.amazonaws.com/coworking-analytics-repo:3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        envFrom:
        - configMapRef:
            name: coworking-config
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: coworking-config
              key: DB_USERNAME
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: coworking-config
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: coworking-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: coworking-config
              key: DB_PORT
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: coworking-secret
              key: dbPassword
      restartPolicy: Always